-- =====================================================================
-- 도서관 대출 시스템 스키마 (H2 PostgreSQL 모드 / PostgreSQL 공용)
-- JPA ddl-auto 를 쓰지 않고 이 파일로 스키마를 관리한다.
-- =====================================================================

-- 역할
CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL
);

-- 사용자 (역할은 1개)
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50)  NOT NULL,
    password            VARCHAR(100) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    email               VARCHAR(200) NOT NULL,
    role_id             BIGINT       NOT NULL REFERENCES roles (id),
    failed_login_count  INT          NOT NULL DEFAULT 0,
    locked              BOOLEAN      NOT NULL DEFAULT FALSE,
    locked_at           TIMESTAMP,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 이름을 붙여 두어 동시 가입 경합 시 위반 제약을 식별해 409 로 번역한다
    CONSTRAINT uk_users_username UNIQUE (username)
);

-- Refresh 토큰 (원문 대신 SHA-256 해시만 저장)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMP   NOT NULL,
    revoked_at  TIMESTAMP,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);

-- 메뉴 (화면 단위)
CREATE TABLE IF NOT EXISTS menus (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    path        VARCHAR(200) NOT NULL,
    sort_order  INT          NOT NULL
);

-- 메뉴 액션 (READ: 화면 진입·조회, ACTION: 버튼 동작)
CREATE TABLE IF NOT EXISTS menu_actions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id      BIGINT       NOT NULL REFERENCES menus (id),
    code         VARCHAR(50)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    action_type  VARCHAR(10)  NOT NULL,
    CONSTRAINT uk_menu_actions_code UNIQUE (menu_id, code),
    CONSTRAINT ck_menu_actions_type CHECK (action_type IN ('READ', 'ACTION'))
);

-- 액션이 허용하는 URL (한 액션에 여러 개, 같은 URL 이 여러 액션에 걸리면 OR)
-- uk_action_urls 위반(동시 추가 경합)은 409 DUPLICATE_ACTION_URL 로 번역한다
CREATE TABLE IF NOT EXISTS action_urls (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id    BIGINT       NOT NULL REFERENCES menu_actions (id),
    http_method  VARCHAR(10)  NOT NULL,
    url_pattern  VARCHAR(200) NOT NULL,
    CONSTRAINT uk_action_urls UNIQUE (action_id, http_method, url_pattern)
);

-- 역할별 부여 액션
CREATE TABLE IF NOT EXISTS role_actions (
    role_id    BIGINT NOT NULL REFERENCES roles (id),
    action_id  BIGINT NOT NULL REFERENCES menu_actions (id),
    PRIMARY KEY (role_id, action_id)
);

-- 로그인만 되어 있으면 호출 가능한 URL
CREATE TABLE IF NOT EXISTS authenticated_urls (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    http_method  VARCHAR(10)  NOT NULL,
    url_pattern  VARCHAR(200) NOT NULL,
    description  VARCHAR(200),
    CONSTRAINT uk_authenticated_urls UNIQUE (http_method, url_pattern)
);

-- 사용자 접속 조건 (값이 비어 있으면 해당 항목은 제한 없음)
CREATE TABLE IF NOT EXISTS user_access_conditions (
    user_id       BIGINT PRIMARY KEY REFERENCES users (id),
    allowed_ips   VARCHAR(2000),
    valid_from    DATE,
    valid_to      DATE,
    allowed_days  VARCHAR(40),
    start_time    TIME,
    end_time      TIME,
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- API Key (원문은 저장하지 않고 SHA-256 해시만 저장)
CREATE TABLE IF NOT EXISTS api_keys (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    key_prefix     VARCHAR(8)   NOT NULL,
    key_hash       VARCHAR(64)  NOT NULL UNIQUE,
    owner_user_id  BIGINT       NOT NULL REFERENCES users (id),
    expires_at     TIMESTAMP,
    revoked_at     TIMESTAMP,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at   TIMESTAMP
);

-- API Key 에 부여한 액션 (사용자 역할과 같은 액션 체계)
CREATE TABLE IF NOT EXISTS api_key_actions (
    api_key_id  BIGINT NOT NULL REFERENCES api_keys (id),
    action_id   BIGINT NOT NULL REFERENCES menu_actions (id),
    PRIMARY KEY (api_key_id, action_id)
);

-- API Key 허용 IP (선택)
CREATE TABLE IF NOT EXISTS api_key_allowed_ips (
    api_key_id  BIGINT      NOT NULL REFERENCES api_keys (id),
    ip          VARCHAR(50) NOT NULL,
    PRIMARY KEY (api_key_id, ip)
);

-- 도서
CREATE TABLE IF NOT EXISTS books (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn                VARCHAR(20)  NOT NULL,
    title               VARCHAR(200) NOT NULL,
    author              VARCHAR(100) NOT NULL,
    publisher           VARCHAR(100) NOT NULL,
    category            VARCHAR(50)  NOT NULL,
    total_quantity      INT          NOT NULL,
    available_quantity  INT          NOT NULL,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 낙관적 락 버전. 도서 수정이 동시에 커밋된 대출·반납의 재고 변경을 덮어쓰지 않게 한다(재고 증감 UPDATE 도 함께 올린다)
    version             BIGINT       NOT NULL DEFAULT 0,
    -- 이름을 붙여 두어 동시 등록·수정 경합 시 위반 제약을 식별해 409 DUPLICATE_ISBN 으로 번역한다
    CONSTRAINT uk_books_isbn UNIQUE (isbn),
    CONSTRAINT ck_books_quantity CHECK (available_quantity >= 0 AND available_quantity <= total_quantity)
);

-- 대출
CREATE TABLE IF NOT EXISTS loans (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users (id),
    book_id        BIGINT      NOT NULL REFERENCES books (id),
    loan_date      DATE        NOT NULL,
    due_date       DATE        NOT NULL,
    returned_date  DATE,
    status         VARCHAR(10) NOT NULL,
    CONSTRAINT ck_loans_status CHECK (status IN ('LOANED', 'RETURNED', 'OVERDUE'))
);
CREATE INDEX IF NOT EXISTS idx_loans_user_status ON loans (user_id, status);
