package com.example.SpringSecurity_Example.model.knox;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
public class KnoxEmployee {
    private String accountStatus;
    private String busiCode;
    private String busiName;
    private String companyCode;
    private String companyName;
    private String country;
    private String defaultCompanyCode;
    private String departmentCode;
    private String departmentName;
    private String description;
    private String emailAddress;
    private String employeeNumber;
    private String employeeStatus;
    private String employeeType;
    private String enBusiName;
    private String enCompanyName;
    private String enDepartmentName;
    private String enDiscription;
    private String enFullName;
    private String enGivenName;
    private String enGradeName;
    private String enOfficeAddress;
    private String enRegionName;
    private String enSendBusiName;
    private String enSendCompanyName;
    private String enSendDepartmentName;
    private String enSendGradeName;
    private String enSendRegionName;
    private String enSendSubOrgName;
    private String enSendTitleName;
    private String enSirName;
    private String enSubOrgName;
    private String enTitleName;
    private String epId;
    private String executiveYn;
    private String externalEmailAddress;
    private String fullName;
    private String givenName;
    private String gradeName;
    private String gradeTitleIndiCode;
    private String inDepartmentCode;
    private String inDepartmentName;
    private String jobName;
    private String jobCode;
    private String localStaffYn;
    private String mobile;
    private String nickName;
    private String officeAddress;
    private String officeDetailAddress;
    private String officeFaxNumber;
    private String officeZipCode;
    private String officeTelNumber;
    private String preferredLanguage;
    private String realNameYn;
    private String regionCode;
    private String regionName;
    private String securityLevel;
    private String sendBusiCde;
    private String sendCompanyCode;
    private String sendCompanyName;
    private String sendDepartmentCode;
    private String sendDepartmentName;
    private String sendGradeName;
    private String sendGradeTitleIndiCode;
    private String sendRegionCode;
    private String sendSecurityLevel;
    private String sendSubOrgCode;
    private String sendSubOrgName;
    private String sendTitleName;
    private String sendTitleCode;
    private String sendTitleSortOrder;
    private String serverLocation;
    private String sirName;
    private String subOrgCode;
    private String subOrgName;
    private String titleName;
    private String titleCode;
    private String titleSortOrder;
    private String openCode;
    private String userId;
    private String voipNumber;
    private String withdrawDate;
    private String epIdExpiryDate;
    private String timeZone;
}
